highlighter: rouge
markdown: rdiscount
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
gems: [jekyll-paginate]
port: 4000
safe: true
url: https://davecastlevania.github.io/
author: David Castaneda

# edit this section with your information
# biomadeira.github.io - all contents run on /vitae/
# for a normal use at the base of the server change it to "/"
baseurl: /
title: David A Castaneda's Resume
name: David A Castaneda
email: d.alfonso.castaneda@gmail.com
email_full: mailto:d.alfonso.castaneda@gmail.com
website: My Portfolio
website_full: https://polar-harbor-94853.herokuapp.com
github: davecastlevania
# twitter: davecastlevania
tel: +1 423 521 0386
tel_full: tel:+4235210386
google_maps: 'https://www.google.com/maps/place/Atlanta+GA'
address1: 1441 Woodmont Ln NW
address2: 423
postcode: 30318
city: Atlanta, GA
country: United States
google_analytics: UA-69300817-1

# needed for travis-ci build
exclude: [vendor]
